// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe-uh_D3ZetBzLLyx3rXLkR9B-zh8iyd0',
    appId: '1:715441558472:web:521f215cb01834cc7226fd',
    messagingSenderId: '715441558472',
    projectId: 'kokotoba-269cb',
    authDomain: 'kokotoba-269cb.firebaseapp.com',
    storageBucket: 'kokotoba-269cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2mUluBZrO5qvsQSAX7LbWuHlYt6Nq8fo',
    appId: '1:715441558472:android:03fc4c55549766ec7226fd',
    messagingSenderId: '715441558472',
    projectId: 'kokotoba-269cb',
    storageBucket: 'kokotoba-269cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOzPVYaIOLH3bOwZggNPiIni5R2ppA_M',
    appId: '1:715441558472:ios:ed9e755d6478bfc47226fd',
    messagingSenderId: '715441558472',
    projectId: 'kokotoba-269cb',
    storageBucket: 'kokotoba-269cb.appspot.com',
    iosClientId: '715441558472-d8topnvpevn5ltrucuefs8kpc9t42jv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOzPVYaIOLH3bOwZggNPiIni5R2ppA_M',
    appId: '1:715441558472:ios:ed9e755d6478bfc47226fd',
    messagingSenderId: '715441558472',
    projectId: 'kokotoba-269cb',
    storageBucket: 'kokotoba-269cb.appspot.com',
    iosClientId: '715441558472-d8topnvpevn5ltrucuefs8kpc9t42jv8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
